---
- name: Patch and reboot servers
  hosts: centos
  become: "yes"
  vars:
    yum_name: "*"
    yum_state: latest
    yum_exclude: ""
  tasks:

    - name: upgrade packages via yum
      yum:
        name={{ yum_name }}
        state={{ yum_state }}
        exclude={{ yum_exclude }}
      register: yumcommandout
      when:
        - (ansible_facts['distribution_major_version'] == '6') or
          (ansible_facts['distribution_major_version'] >= '7')

    - debug:
        var: yumcommandout

    - name: Print errors if yum failed
      debug:
        msg: "yum update failed"
      when: yumcommandout is not defined

    - name: Reboot the box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: "'all packages are up to date' in yumcommandout.results"
      register: reboot_stat

    - debug:
        msg: "{{ ansible_fqdn }} is back up and running"
      when: reboot_stat is changed

    - debug: 
        msg: "{{ ansible_fqdn }} is patched at latest: {{ ansible_kernel }}"
      when: reboot_stat is not changed
